---
baseUrl: http://mobilerobot.io/
theme: focus
publishDir: docs
canonifyURLs: true
languageCode: en-us
title: "Mobile Robot I/O"
#googleAnalytics: UA-138892687-1
categories:
  - Electronics
  - Software
  - Mechanics
params:
  author: Rusty Eddy
---
